"""
Phase 10: Batch drift monitoring.

`DriftMonitor.analyze_batch()` is the single public entry point. It is
DELIBERATELY a pure, passive analysis over data the caller already has —
it does NOT call the model, the feature pipeline, or the behavioral state
engine itself. The caller is responsible for supplying a batch that
already contains the monitored raw columns, the already-computed `bhv_*`
behavioral columns (generated by the approved Phase 4/6 engine, never
recomputed here), and the already-computed risk scores/decisions (the
approved Phase 5 policy's own output). This is what "do not create a
second inconsistent behavioral-feature implementation" means in practice:
this module has no feature-generation code of its own to be inconsistent
with.

Batch-only, never single-transaction: `analyze_batch` requires an entire
DataFrame. There is no equivalent single-row method, by design — the brief
is explicit that drift cannot be meaningfully declared from one
transaction.
"""

from __future__ import annotations

import threading
from collections import defaultdict
from datetime import datetime, timezone

from src.drift.detectors import compute_numeric_drift, compute_categorical_drift, compute_decision_drift
from src.drift.report import build_drift_report

# Below this batch size, PSI/KS results are still computed (never skipped
# outright — a partial, honestly-caveated signal is more useful than
# silence) but flagged as low-confidence: with very few observations, the
# 10-bin reference histogram is under-populated per bin and both PSI and
# KS become noisy/unreliable estimators. 30 is a common statistical rule
# of thumb for "enough observations for basic distributional comparisons,"
# not a rigorously derived value for this specific application —
# documented as a project-configurable constant, like the PSI severity
# thresholds in `src/drift/detectors.py`.
MIN_BATCH_SIZE = 30


class DriftMonitor:
    def __init__(self, reference_profile: dict):
        self.reference_profile = reference_profile
        self._lock = threading.Lock()
        self.batches_analyzed = 0
        self.severity_counts: dict = defaultdict(int)
        self.latest_report: dict | None = None

    def analyze_batch(self, batch_df, risk_scores=None, decisions=None) -> dict:
        n = len(batch_df)
        warnings = []
        low_confidence = n < MIN_BATCH_SIZE
        if low_confidence:
            warnings.append(
                f"Batch size ({n}) is below the minimum recommended size "
                f"({MIN_BATCH_SIZE}); drift results below have limited "
                f"statistical confidence and should not be treated as a "
                f"reliable signal on their own."
            )

        feature_results = []
        for feature_name, ref_entry in self.reference_profile.get("numeric", {}).items():
            if feature_name in batch_df.columns:
                result = compute_numeric_drift(ref_entry, batch_df[feature_name])
                feature_results.append({"feature": feature_name, "type": "numeric", **result})
        for feature_name, ref_entry in self.reference_profile.get("categorical", {}).items():
            if feature_name in batch_df.columns:
                result = compute_categorical_drift(ref_entry, batch_df[feature_name])
                feature_results.append({"feature": feature_name, "type": "categorical", **result})
                if result["new_categories"]:
                    warnings.append(
                        f"'{feature_name}': {len(result['new_categories'])} category value(s) "
                        f"never seen in the reference distribution: {result['new_categories'][:10]}"
                        + (" (truncated)" if len(result["new_categories"]) > 10 else "")
                    )
        for feature_name, ref_entry in self.reference_profile.get("behavioral", {}).items():
            if feature_name in batch_df.columns:
                result = compute_numeric_drift(ref_entry, batch_df[feature_name])
                feature_results.append({"feature": feature_name, "type": "behavioral", **result})

        risk_score_result = None
        if risk_scores is not None:
            risk_score_result = compute_numeric_drift(self.reference_profile["risk_score"], risk_scores)

        decision_result = None
        if decisions is not None:
            decision_result = compute_decision_drift(self.reference_profile["decision"], decisions)

        report = build_drift_report(
            batch_size=n,
            reference_metadata=self.reference_profile.get("metadata", {}),
            feature_results=feature_results,
            risk_score_result=risk_score_result,
            decision_result=decision_result,
            low_confidence=low_confidence,
            warnings=warnings,
            timestamp=datetime.now(timezone.utc).isoformat(),
        )

        with self._lock:
            self.batches_analyzed += 1
            self.severity_counts[report["overall_severity"]] += 1
            self.latest_report = report

        return report

    def summary(self) -> dict:
        """Lightweight, Phase-9-style observability summary — reports the
        LATEST known state, never triggers a new analysis (see
        `src/api/main.py`'s `/drift/summary`, which is intentionally
        read-only and cheap, unlike `/drift/analyze`)."""
        with self._lock:
            return {
                "batches_analyzed": self.batches_analyzed,
                "severity_counts": dict(self.severity_counts),
                "latest_status": self.latest_report["overall_severity"] if self.latest_report else None,
                "latest_timestamp": self.latest_report["timestamp"] if self.latest_report else None,
                "latest_explanation": self.latest_report["overall_explanation"] if self.latest_report else None,
            }
